import { wrap } from '@liquid-labs/wrap-text'

export const COMPLY_SERVER_CLI_NAME = () => 'comply-server'

export const COMPLY_GENERATED_FILE_NOTICE = ({ builderNPMName, commentToken }) => {
  if (!commentToken.endsWith(' ')) {
    commentToken += ' '
  }
  return wrap(`This file was generated by ${builderNPMName}. Refer to https://npmjs.com/package/${builderNPMName} for further details`,
    {
      prefix : commentToken,
      width  : 80
    })
}
