import { wrapText } from '@liquid-labs/wrap-text'

const CATALYST_CLI_NAME = () => process.env.CATALYST_CLI_NAME || 'catalyst'
const CATALYST_GENERATED_FILE_NOTICE = ({ builderNPMName,  commentToken }) => {
  if (!commentToken.endsWith(' ')) {
    commentToken += ' '
  }
  wrapText(`This file was generated by ${builderNPMName}. Refer to https://npmjs.com/package/${builderNPMName} for furtehr details`,
    {
      prefix: commentToken,
      width: 80
    })
}
